# Generated by Django 3.2.8 on 2021-11-23 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegram',
            name='updated_now',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='telegram',
            name='updated',
            field=models.DateTimeField(),
        ),
    ]
