# Generated by Django 3.2.8 on 2021-11-24 23:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_telegram_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegram',
            name='updated_now',
        ),
        migrations.AddField(
            model_name='telegram',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='telegram',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
