# Generated by Django 3.2.8 on 2021-11-25 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20211124_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegram',
            name='created',
        ),
        migrations.RemoveField(
            model_name='telegram',
            name='telegram_id',
        ),
        migrations.RemoveField(
            model_name='telegram',
            name='token',
        ),
        migrations.RemoveField(
            model_name='telegram',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='telegram',
            name='user',
        ),
    ]
