# Generated by Django 3.2.8 on 2021-11-25 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0011_auto_20211124_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.CharField(blank=True, max_length=2, null=True)),
                ('minuts', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='telegram',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telegram',
            name='telegram_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegram',
            name='token',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegram',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='telegram',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
