# Generated by Django 3.2.8 on 2021-11-28 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20211125_0150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventypes',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-created']},
        ),
    ]
