# Generated by Django 3.2.8 on 2021-11-29 00:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0016_auto_20211128_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minuts', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Eventypes',
            new_name='Availabilities',
        ),
    ]
