# Generated by Django 3.2.8 on 2021-11-29 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20211128_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilities',
            name='start_interval',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.startinterval'),
        ),
    ]
