# Generated by Django 3.2.8 on 2021-11-29 01:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_availabilities_start_interval'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='startinterval',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='startinterval',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
