# Generated by Django 3.2.8 on 2021-11-29 14:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0020_auto_20211128_2206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='duration',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='group',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
