# Generated by Django 4.0 on 2022-08-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_event_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='availabilities',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
