# Generated by Django 4.0 on 2022-08-29 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_group_type_alter_availabilities_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='types',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.group_type'),
        ),
    ]
