# Generated by Django 4.0 on 2022-08-29 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_group_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='types',
            new_name='type',
        ),
    ]
