# Generated by Django 4.0 on 2022-09-05 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_rename_types_group_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opening_hours_days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Opening_hours_notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Opening_hours_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Opening_hours_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Opening_hours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.opening_hours_days')),
                ('notification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.opening_hours_notification')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.opening_hours_status')),
                ('time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.opening_hours_time')),
            ],
        ),
    ]
