# Generated by Django 4.0 on 2022-09-05 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base', '0026_opening_hours_days_opening_hours_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opening_hours',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
