# Generated by Django 4.0 on 2022-09-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_opening_hours_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping', models.BooleanField()),
                ('shipping_destination', models.CharField(blank=b'I01\n', choices=[('residencial', 'Residencial'), ('comercial', 'Comercial')], max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='event',
            name='group',
        ),
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
        migrations.DeleteModel(
            name='Availabilities',
        ),
        migrations.DeleteModel(
            name='Duration',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='StartInterval',
        ),
    ]
