# Generated by Django 4.0 on 2022-09-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_shippinginfo_remove_event_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(help_text='Enter a name for the event. This is a required field and is limited to 70 characters.', max_length=70)),
                ('recurring_event', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', help_text='Is this a one off event or will it recur? Selecting Yes will open up additional fields.', max_length=5)),
                ('recurrence_pattern', models.CharField(choices=[('---', '---'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='---', help_text='Select the recurrence pattern for this event.', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='ShippingInfo',
        ),
    ]
