# Generated by Django 4.0 on 2022-09-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.IntegerField(choices=[(1, 'k_v'), (2, 'pipe')], default=1)),
                ('component_name', models.CharField(max_length=200)),
                ('branch_number_collectors', models.IntegerField(default=4)),
                ('k_v', models.FloatField(default=1)),
                ('DI', models.FloatField(default=0.025)),
                ('length', models.FloatField(default=1)),
                ('branch_volumetric_flow_rate', models.FloatField(default=0)),
                ('branch_mass_flow_rate', models.FloatField(default=0)),
                ('velocity', models.FloatField(default=0)),
                ('reynolds', models.FloatField(default=0)),
                ('friction_coefficient', models.FloatField(default=0)),
                ('pressure_loss', models.FloatField(default=0)),
            ],
        ),
    ]
