# Generated by Django 4.0 on 2022-09-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_alter_opening_hours_close_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(blank=True, help_text='Enter a name for the event. This is a required field and is limited to 70 characters.', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='recurrence_pattern',
            field=models.CharField(blank=True, choices=[('---', '---'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='---', help_text='Select the recurrence pattern for this event.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='recurring_event',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], default='No', help_text='Is this a one off event or will it recur? Selecting Yes will open up additional fields.', max_length=5, null=True),
        ),
    ]
