# Generated by Django 4.0 on 2022-09-15 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_opening_hours_timezone_alter_event_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='opening_hours',
            name='voice_messages',
            field=models.CharField(blank=True, choices=[('inactivated', 'Inactivate'), ('activated', 'Activate')], default='Inactivate', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='opening_hours',
            name='voice_messages_notification',
            field=models.CharField(blank=True, choices=[('on', 'On'), ('off', 'Off')], default='Off', max_length=10, null=True),
        ),
    ]
