# Generated by Django 4.0 on 2022-09-21 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_event_close_time_event_open_time_event_weekdays'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Component',
        ),
        migrations.DeleteModel(
            name='Media',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
