# Generated by Django 4.0 on 2022-09-22 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_delete_opening_hours_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='recurrence_pattern',
        ),
        migrations.RemoveField(
            model_name='event',
            name='recurring_event',
        ),
        migrations.RemoveField(
            model_name='event',
            name='starts_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='event',
            name='weekdays',
        ),
    ]
