# Generated by Django 4.0 on 2022-09-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0052_weekday_weekdaysquedules_delete_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekday',
            name='availability',
        ),
        migrations.AddField(
            model_name='weekday',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
