# Generated by Django 4.0 on 2022-09-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0053_remove_weekday_availability_weekday_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekday',
            name='name',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
