# Generated by Django 4.0 on 2022-09-24 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0055_alter_weekdaysquedules_close_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekday',
            name='available',
        ),
        migrations.AddField(
            model_name='weekdaysquedules',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
