# Generated by Django 4.0 on 2022-09-27 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_remove_weekday_available_weekdaysquedules_available'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WeekdaySquedules',
            new_name='MondaySquedules',
        ),
    ]
