# Generated by Django 4.0 on 2022-09-27 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0057_rename_weekdaysquedules_mondaysquedules'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mondaysquedules',
            old_name='close_time',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='mondaysquedules',
            old_name='open_time',
            new_name='start_time',
        ),
    ]
