# Generated by Django 4.0 on 2022-09-28 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base', '0058_rename_close_time_mondaysquedules_end_time_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Weekday',
            new_name='Agenda',
        ),
        migrations.AlterModelOptions(
            name='agenda',
            options={'verbose_name_plural': 'agenda'},
        ),
        migrations.AlterModelOptions(
            name='mondaysquedules',
            options={'verbose_name': 'Monday', 'verbose_name_plural': 'monday'},
        ),
        migrations.RenameField(
            model_name='mondaysquedules',
            old_name='weekday',
            new_name='agenda',
        ),
    ]
