# Generated by Django 4.0 on 2022-09-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_rename_weekday_agenda_alter_agenda_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='increments',
            field=models.CharField(choices=[('15', '15 min'), ('30', '30 min'), ('45', '45 min'), ('60', '60 min')], default='30 min', max_length=50, null=True),
        ),
    ]
