# Generated by Django 4.0 on 2022-10-02 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base', '0060_agenda_increments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Opening_hours',
            new_name='Settings',
        ),
    ]
