# Generated by Django 4.0 on 2022-11-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0062_alter_settings_close_time_alter_settings_open_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='monday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mondaysquedules',
            name='agenda_name',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='mondaysquedules',
            name='end_time',
            field=models.CharField(choices=[('AM', (('0', '0h'), ('1', '1h'), ('2', '2h'), ('3', '3h'), ('4', '4h'), ('5', '5h'), ('6', '6h'), ('7', '7h'), ('8', '8h'), ('9', '9h'), ('10', '10h'), ('11', '11h'))), ('PM', (('12', '12h'), ('13', '13h'), ('14', '14h'), ('15', '15h'), ('16', '16h'), ('17', '17h'), ('18', '18h'), ('19', '19h'), ('20', '20h'), ('21', '21h'), ('22', '22h'), ('23', '23h')))], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mondaysquedules',
            name='start_time',
            field=models.CharField(choices=[('AM', (('0', '0h'), ('1', '1h'), ('2', '2h'), ('3', '3h'), ('4', '4h'), ('5', '5h'), ('6', '6h'), ('7', '7h'), ('8', '8h'), ('9', '9h'), ('10', '10h'), ('11', '11h'))), ('PM', (('12', '12h'), ('13', '13h'), ('14', '14h'), ('15', '15h'), ('16', '16h'), ('17', '17h'), ('18', '18h'), ('19', '19h'), ('20', '20h'), ('21', '21h'), ('22', '22h'), ('23', '23h')))], max_length=50, null=True),
        ),
    ]
