# Generated by Django 4.0 on 2022-11-19 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0063_agenda_monday_mondaysquedules_agenda_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mondaysquedules',
            name='agenda_name',
        ),
        migrations.AddField(
            model_name='agenda',
            name='tuesday',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='name',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.CreateModel(
            name='TuesdaySquedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
                ('start_time', models.CharField(choices=[('AM', (('0', '0h'), ('1', '1h'), ('2', '2h'), ('3', '3h'), ('4', '4h'), ('5', '5h'), ('6', '6h'), ('7', '7h'), ('8', '8h'), ('9', '9h'), ('10', '10h'), ('11', '11h'))), ('PM', (('12', '12h'), ('13', '13h'), ('14', '14h'), ('15', '15h'), ('16', '16h'), ('17', '17h'), ('18', '18h'), ('19', '19h'), ('20', '20h'), ('21', '21h'), ('22', '22h'), ('23', '23h')))], max_length=50, null=True)),
                ('end_time', models.CharField(choices=[('AM', (('0', '0h'), ('1', '1h'), ('2', '2h'), ('3', '3h'), ('4', '4h'), ('5', '5h'), ('6', '6h'), ('7', '7h'), ('8', '8h'), ('9', '9h'), ('10', '10h'), ('11', '11h'))), ('PM', (('12', '12h'), ('13', '13h'), ('14', '14h'), ('15', '15h'), ('16', '16h'), ('17', '17h'), ('18', '18h'), ('19', '19h'), ('20', '20h'), ('21', '21h'), ('22', '22h'), ('23', '23h')))], max_length=50, null=True)),
                ('agenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.agenda')),
            ],
            options={
                'verbose_name': 'Tuesday',
                'verbose_name_plural': 'tuesday',
            },
        ),
    ]
