# Generated by Django 4.1 on 2022-11-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0068_agenda_wednesday_wednesdaysquedules_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='friday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agenda',
            name='saturday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agenda',
            name='sunday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agenda',
            name='thursday',
            field=models.BooleanField(default=True),
        ),
    ]
