# Generated by Django 4.1 on 2022-11-27 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0069_agenda_friday_agenda_saturday_agenda_sunday_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MondaySquedules',
            new_name='MondaySchedules',
        ),
    ]
