# Generated by Django 4.1 on 2022-11-27 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0071_rename_tuesdaysquedules_tuesdayschedules'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WednesdaySquedules',
            new_name='WednesdaySchedules',
        ),
    ]
