# Generated by Django 4.1 on 2022-11-27 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0072_rename_wednesdaysquedules_wednesdayschedules'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ThursdaySquedules',
            new_name='ThursdaySchedules',
        ),
    ]
