# Generated by Django 4.1 on 2022-11-27 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0073_rename_thursdaysquedules_thursdayschedules'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FridaySquedules',
            new_name='FridaySchedules',
        ),
    ]
