# Generated by Django 4.1 on 2022-11-27 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0074_rename_fridaysquedules_fridayschedules'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SaturdaySquedules',
            new_name='SaturdaySchedules',
        ),
    ]
