# Generated by Django 4.1 on 2022-11-27 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0075_rename_saturdaysquedules_saturdayschedules'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SundaySquedules',
            new_name='SundaySchedules',
        ),
    ]
