# Generated by Django 4.1 on 2022-12-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0076_rename_sundaysquedules_sundayschedules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='friday',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='monday',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='saturday',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='sunday',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='thursday',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='tuesday',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='wednesday',
            field=models.BooleanField(),
        ),
    ]
